//
//  Vulpes-Bridging-Header.h
//  vulpes-browser
//
//  Bridging header to expose libvulpes C API to Swift.
//  This allows Swift code to call the Zig core library.
//

#ifndef Vulpes_Bridging_Header_h
#define Vulpes_Bridging_Header_h

// Include the libvulpes C API header
// This is generated by `zig build` and installed to zig-out/include/
#include "vulpes.h"

#endif /* Vulpes_Bridging_Header_h */
